# -*- coding: utf-8 -*-
"""FinSecureDB_App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3gKpj9QQkJ0ly9jQp82l7wFpEObyurH
"""

# ====================================================================
#            FinSecureDB - Streamlit Web Application
# ====================================================================
# This app provides a GUI for your bank database, fulfilling
# project deliverables #8 (CRUD), #9 (Features), and #11 (Code snippets).
#
# To run this:
# 1. Open your terminal or command prompt.
# 2. Make sure you have the required libraries:
#    pip install streamlit mysql-connector-python pandas
# 3. Navigate to the directory where this file is saved.
# 4. Run:
#    streamlit run app.py
# ====================================================================

import streamlit as st
import mysql.connector
import pandas as pd
from datetime import date

# ====================================================================
# 1. DATABASE CONNECTION
# ====================================================================

# We use @st.cache_resource to create a single connection pool
# that all users/sessions can share. This is the modern
# Streamlit way to handle database connections.
@st.cache_resource
def get_db_connection(host, user, password, database):
    """Creates a connection pool to the MySQL database."""
    try:
        connection = mysql.connector.connect(
            host=host,
            user=user,
            password=password,
            database=database
        )
        return connection
    except mysql.connector.Error as err:
        st.error(f"Error connecting to database: {err}")
        return None

# Helper function to run queries
def run_query(conn, query, params=None):
    """Executes a query and returns a DataFrame."""
    try:
        with conn.cursor(dictionary=True) as cursor:
            cursor.execute(query, params)
            if cursor.description:
                df = pd.DataFrame(cursor.fetchall())
            else:
                df = pd.DataFrame()
            conn.commit()
            return df
    except mysql.connector.Error as err:
        st.error(f"Query Error: {err}")
        return pd.DataFrame()

# Helper function to call procedures
def call_procedure(conn, procedure_name, args=()):
    """Calls a stored procedure and returns the result."""
    try:
        with conn.cursor(dictionary=True) as cursor:
            cursor.callproc(procedure_name, args)
            results = []
            for result in cursor.stored_results():
                results.append(pd.DataFrame(result.fetchall()))
            conn.commit()
            return results
    except mysql.connector.Error as err:
        st.error(f"Procedure Error: {err}")
        return None

# ====================================================================
# 2. APP SIDEBAR & NAVIGATION
# ====================================================================

st.set_page_config(page_title="FinSecureDB", layout="wide")

# Get DB credentials from the user
st.sidebar.title("Database Connection")
st.sidebar.info("Enter your MySQL credentials to connect to the `bankmanagement` database.")

if 'db_host' not in st.session_state:
    st.session_state.db_host = 'localhost'
if 'db_user' not in st.session_state:
    st.session_state.db_user = 'root'
if 'db_password' not in st.session_state:
    st.session_state.db_password = ''
if 'db_name' not in st.session_state:
    st.session_state.db_name = 'bankmanagement'
if 'db_conn' not in st.session_state:
    st.session_state.db_conn = None

st.session_state.db_host = st.sidebar.text_input("Host", st.session_state.db_host)
st.session_state.db_user = st.sidebar.text_input("User", st.session_state.db_user)
st.session_state.db_password = st.sidebar.text_input("Password", st.session_state.db_password, type="password")
st.session_state.db_name = st.sidebar.text_input("Database", st.session_state.db_name)

# Button to connect
if st.sidebar.button("Connect to Database"):
    conn = get_db_connection(
        st.session_state.db_host,
        st.session_state.db_user,
        st.session_state.db_password,
        st.session_state.db_name
    )
    if conn and conn.is_connected():
        st.session_state.db_conn = conn
        st.sidebar.success("Successfully connected!")
    else:
        st.session_state.db_conn = None
        st.sidebar.error("Connection failed. Check credentials.")

# Navigation
st.sidebar.title("Navigation")
page = st.sidebar.radio("Go to", [
    "Home",
    "View All Tables",
    "Customer Management (CRUD)",
    "Make a Loan Payment (Procedure)",
    "Bank Reports (Complex Queries)"
])

# ====================================================================
# 3. PAGE: HOME
# ====================================================================
def page_home():
    st.title("Welcome to FinSecureDB")
    st.image("https://placehold.co/800x200/003366/FFFFFF?text=FinSecureDB+Dashboard", use_column_width=True)
    st.header("Database Management System Mini Project")
    st.write("""
    This is a web-based GUI for the FinSecureDB (Bank Management) database.

    **Instructions:**
    1.  **Connect to the Database:** Use the sidebar to enter your MySQL credentials.
    2.  **Navigate:** Use the sidebar radio buttons to explore different app features.

    **This app demonstrates all key project deliverables:**
    * **CRUD Operations:** See the 'Customer Management' page for a full example.
    * **Procedure Integration:** The 'Make a Loan Payment' page calls the `sp_MakeLoanPayment` procedure.
    * **Complex Query Reports:** The 'Bank Reports' page runs and displays the Join, Aggregate, and Nested queries.
    """)
    if not st.session_state.db_conn or not st.session_state.db_conn.is_connected():
        st.error("Please connect to the database using the sidebar to begin.")

# ====================================================================
# 4. PAGE: VIEW ALL TABLES
# ====================================================================
def page_view_tables():
    st.title("View All Tables")
    st.write("Select a table to view its raw data.")

    table_names = [
        "account", "atm", "bank", "branch", "customer",
        "employee", "loans", "manager", "payment", "transaction"
    ]
    table_to_view = st.selectbox("Select a table", table_names)

    if st.button(f"Fetch Data for {table_to_view}"):
        df = run_query(st.session_state.db_conn, f"SELECT * FROM {table_to_view}")
        if not df.empty:
            st.dataframe(df)
        else:
            st.warning("No data found in this table.")

# ====================================================================
# 5. PAGE: CUSTOMER MANAGEMENT (CRUD)
# ====================================================================
def page_customer_crud():
    st.title("Customer Management (CRUD Example)")
    st.write("This page demonstrates full Create, Read, Update, and Delete operations for the `customer` table.")

    st.header("Read: All Customers")
    customers_df = run_query(st.session_state.db_conn, "SELECT * FROM customer ORDER BY Customer_ID")
    st.dataframe(customers_df)

    # --- CREATE ---
    st.header("Create: Add New Customer")
    with st.form("add_customer_form"):
        col1, col2 = st.columns(2)
        with col1:
            name = st.text_input("Name")
            dob = st.date_input("Date of Birth", min_value=date(1920, 1, 1), value=date(2000, 1, 1))
            gender = st.selectbox("Gender", ["Male", "Female", "Other"])
            email = st.text_input("Email")
            phone = st.text_input("Phone (e.g., 9876543210)")
        with col2:
            street = st.text_input("Street")
            city = st.text_input("City")
            state = st.text_input("State")
            pincode = st.text_input("Pincode (e.g., 560001)")
            balance = st.number_input("Initial Balance (Customer-level)", min_value=0.0, value=0.0, step=100.0)

        submitted_create = st.form_submit_button("Add Customer")
        if submitted_create:
            # Get next Customer_ID
            next_id_df = run_query(st.session_state.db_conn, "SELECT MAX(Customer_ID) + 1 AS next_id FROM customer")
            next_id = next_id_df['next_id'][0] if not next_id_df.empty and next_id_df['next_id'][0] else 1

            query = """
            INSERT INTO customer (Customer_ID, Name, DOB, Gender, Email, Phone, Street, City, State, Pincode, Balance)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            params = (next_id, name, dob, gender, email, phone, street, city, state, pincode, balance)
            run_query(st.session_state.db_conn, query, params)
            st.success(f"Successfully added new customer: {name} (ID: {next_id})")
            st.rerun()

    # --- UPDATE ---
    st.header("Update: Edit Customer Details")
    st.write("Select a customer to update their contact information.")

    if not customers_df.empty:
        customer_id_list = customers_df['Customer_ID'].tolist()
        customer_to_edit = st.selectbox("Select Customer_ID to Edit", customer_id_list, format_func=lambda x: f"{x} - {customers_df[customers_df['Customer_ID'] == x]['Name'].values[0]}")

        selected_customer = customers_df[customers_df['Customer_ID'] == customer_to_edit].iloc[0]

        with st.form("update_customer_form"):
            st.write(f"**Editing Customer:** {selected_customer['Name']} (ID: {selected_customer['Customer_ID']})")
            new_email = st.text_input("New Email", value=selected_customer['Email'])
            new_phone = st.text_input("New Phone", value=selected_customer['Phone'])
            new_street = st.text_input("New Street", value=selected_customer['Street'])
            new_city = st.text_input("New City", value=selected_customer['City'])

            submitted_update = st.form_submit_button("Update Customer Info")
            if submitted_update:
                query = """
                UPDATE customer
                SET Email = %s, Phone = %s, Street = %s, City = %s
                WHERE Customer_ID = %s
                """
                params = (new_email, new_phone, new_street, new_city, customer_to_edit)
                run_query(st.session_state.db_conn, query, params)
                st.success(f"Successfully updated customer ID: {customer_to_edit}")
                st.rerun()
    else:
        st.warning("No customers to update.")

    # --- DELETE ---
    st.header("Delete: Remove Customer")
    st.write("Select a customer ID to delete. This is permanent.")

    if not customers_df.empty:
        customer_to_delete = st.selectbox("Select Customer_ID to Delete", customer_id_list, format_func=lambda x: f"{x} - {customers_df[customers_df['Customer_ID'] == x]['Name'].values[0]}", key="delete_select")

        if st.button("Delete Customer", type="primary"):
            st.warning(f"Are you sure you want to delete {customers_df[customers_df['Customer_ID'] == customer_to_delete]['Name'].values[0]}? This cannot be undone.", icon="⚠️")

            if st.button("Yes, I am sure. Delete."):
                query = "DELETE FROM customer WHERE Customer_ID = %s"
                params = (customer_to_delete,)
                run_query(st.session_state.db_conn, query, params)
                st.success(f"Successfully deleted customer ID: {customer_to_delete}")
                st.rerun()
    else:
        st.warning("No customers to delete.")

# ====================================================================
# 6. PAGE: MAKE A LOAN PAYMENT (PROCEDURE)
# ====================================================================
def page_make_payment():
    st.title("Make a Loan Payment")
    st.header("This page calls the `sp_MakeLoanPayment` stored procedure.")

    with st.form("loan_payment_form"):
        st.write("Enter payment details:")
        loan_id = st.number_input("Loan ID", min_value=1, step=1)
        payment_amount = st.number_input("Payment Amount", min_value=0.01, step=100.0)
        payment_mode = st.selectbox("Payment Mode", ["NEFT", "UPI", "Cheque", "Online"])

        submitted_payment = st.form_submit_button("Submit Payment")

        if submitted_payment:
            st.write("Processing payment...")
            args = (loan_id, payment_amount, payment_mode)
            results = call_procedure(st.session_state.db_conn, 'sp_MakeLoanPayment', args)

            if results:
                st.success("Procedure executed successfully!")
                st.write("Response from database:")
                st.dataframe(results[0])
            else:
                st.error("Procedure call failed.")

    st.header("Active Loans")
    st.write("For reference, here are the current loans:")
    loans_df = run_query(st.session_state.db_conn, """
        SELECT l.Loan_ID, c.Name as Customer_Name, l.Amount as Original_Amount, l.Type
        FROM loans l
        JOIN customer c ON l.Customer_ID = c.Customer_ID
    """)
    st.dataframe(loans_df)


# ====================================================================
# 7. PAGE: BANK REPORTS (COMPLEX QUERIES)
# ====================================================================
def page_bank_reports():
    st.title("Bank Reports")
    st.write("This page runs the complex Join, Aggregate, and Nested queries.")

    # --- 1. JOIN QUERY ---
    st.header("Employee Details (JOIN Query)")
    st.write("Lists all employees, their branch name, and their manager's level.")
    join_query = """
        SELECT
            e.Name AS Employee_Name,
            e.Salary,
            b.Branch_Name,
            m.Manager_Level
        FROM
            employee e
        LEFT JOIN
            branch b ON e.Branch_ID = b.Branch_ID
        LEFT JOIN
            manager m ON e.EID = m.EID;
    """
    join_df = run_query(st.session_state.db_conn, join_query)
    st.dataframe(join_df)

    # --- 2. AGGREGATE QUERY ---
    st.header("Branch Salary Report (AGGREGATE Query)")
    st.write("Shows the average salary and number of employees at each branch.")
    agg_query = """
        SELECT
            b.Branch_Name,
            AVG(e.Salary) AS Average_Salary,
            COUNT(e.EID) AS Number_of_Employees
        FROM
            employee e
        JOIN
            branch b ON e.Branch_ID = b.Branch_ID
        GROUP BY
            b.Branch_Name;
    """
    agg_df = run_query(st.session_state.db_conn, agg_query)

    st.dataframe(agg_df)

    # Show a chart
    if not agg_df.empty:
        st.subheader("Average Salary by Branch")
        st.bar_chart(agg_df.set_index("Branch_Name")['Average_Salary'])

    # --- 3. NESTED QUERY ---
    st.header("Large Loan Customer Report (NESTED Query)")
    st.write("Finds all customers who have a loan amount greater than the average of all loan amounts.")
    nested_query = """
        SELECT
            Customer_ID,
            Name,
            Email,
            Phone
        FROM
            customer
        WHERE
            Customer_ID IN (
                SELECT Customer_ID
                FROM loans
                WHERE Amount > (
                    SELECT AVG(Amount) FROM loans
                )
            );
    """
    nested_df = run_query(st.session_state.db_conn, nested_query)
    st.dataframe(nested_df)


# ====================================================================
# 8. MAIN APP LOGIC
# ====================================================================
if not st.session_state.db_conn or not st.session_state.db_conn.is_connected():
    if page not in ["Home"]:
        st.warning("Please connect to the database using the sidebar to use this page.")
    page_home()
else:
    if page == "Home":
        page_home()
    elif page == "View All Tables":
        page_view_tables()
    elif page == "Customer Management (CRUD)":
        page_customer_crud()
    elif page == "Make a Loan Payment (Procedure)":
        page_make_payment()
    elif page == "Bank Reports (Complex Queries)":
        page_bank_reports()